### ISSUE TITLE
web administration

### ISSUE THREAD

**Issue by danielepolencic** [dokku/dokku-rabbitmq#1]
Is there a way to access RabbitMQ administration panel from this?

**Comment by josegonzalez** [comment]
At the moment, no. We're tracking proper port exposing in https://github.com/dokku/dokku-redis/pull/1 . Note, all of these plugins will be in beta until said feature is merged everywhere (and all things are tested in latest dokku).

**Comment by josegonzalez** [comment]
This isn't quite well documented yet, but it works. Here is what you can do:

```shell
dokku rabbitmq:expose <name>
```

Which will have the following output:

```shell
# !     Service is already started
#-----> Service test exposed on port(s) 8671 21472 15631 23317
```

The last port there is the port that has the rabbitmq administration panel. In the future, we'll have some nicer output explaining which port is what...
