### ISSUE TITLE
/var/lib/rabbitmq not mounted to /var/lib/dokku/services

### ISSUE THREAD

**Issue by ebeigarts** [dokku/dokku-rabbitmq#16]
Currently other `dokku/dokku-*` plugins uses `/var/lib/dokku/services/<name>/data` for volumes.
Is there a reason `/var/lib/rabbitmq` is not mounted there?

**Comment by Flink** [comment]
No I think that’s a mistake

**Comment by Flink** [comment]
Fixed by https://github.com/dokku/dokku-rabbitmq/commit/c1331bdfe6a21ed604e831d6ee5bd4bf92e289ae
