### ISSUE TITLE
Enable exposure of management plugin

### ISSUE THREAD

**Issue by imsickofmaps** [dokku/dokku-rabbitmq#21]
You seem to be using the management image from https://hub.docker.com/_/rabbitmq/ but the `expose` command doesn't seem to able to handle exposing the management UI which should be available inside the container on port `15672`.

**Comment by josegonzalez** [comment]
What happens when you run the `expose` command?

**Comment by imsickofmaps** [comment]
> $ dokku rabbitmq:expose app-name-rabbitmq 15672
> !     Service is already started
> 4 ports to be exposed need to be provided

**Comment by josegonzalez** [comment]
It's telling you exactly what you need to do. You need to provide 4 ports to expose the internal `ip:port` mapping. You only provided one.

**Comment by imsickofmaps** [comment]
I struggled to grasp from the code what those ports are going to be used for or the ordering. Is it `mqport_internal mqport_external mgmtport_internal mgmtport_external`?

**Comment by josegonzalez** [comment]
Sure. Once you expose them, the info on which ports map to what will be shown, so you can unexpose and re-expose if the settings were wrong.

**Comment by imsickofmaps** [comment]
Yeah, it's not that. So I did:

> $ dokku rabbitmq:expose app-name-rabbitmq 5672 5673 15672 15673
> !     Service is already started
> -----> Service app-name-rabbitmq exposed on port(s) 5672 5673 15672 15673

Then I ran `docker ps` and found what the mapping actually was:

> 0.0.0.0:5672->5672/tcp, 0.0.0.0:5673->4369/tcp, 0.0.0.0:15673->15672/tcp, 0.0.0.0:15672->35197/tcp

so using this helpful explanation of rabbitmq ports from: http://stackoverflow.com/a/12811593 it looks like the ordering documentation should say:

`dokku rabbitmq:expose app-name-rabbitmq mq_port cluster_resolution cluster_comms mgmt_port`

Which is mapping to the following inside the container:

> mq_port: 5672
> cluster_resolution: 4369
> cluster_comms: 35197
> mgmt_port: 15672

I think it should probably contain a warning to use a firewall to not expose the mapped ports for anything other than the web interface to the outside world because the expose command it going to make your rabbitmq open to the outside world as expose operates on 0.0.0.0

**Comment by josegonzalez** [comment]
When running `dokku rabbitmq:expose`, we now show which ports are exposed where. This information is also available with `dokku rabbitmq:info SERVICE --exposed-ports`.
