### ISSUE TITLE
Access from outside

### ISSUE THREAD

**Issue by sysrun** [dokku/dokku-rabbitmq#22]
Hi,

i'm just trying to open a connection to rabbitmq from "outside" (open mqtt to the "internet") to connect external services. No luck with the "expose" command - i can connect to the webadmin but not to the mqtt port itself. Any ideas?

**Comment by josegonzalez** [comment]
What did you try, and do you have a firewall setup?

**Comment by sysrun** [comment]
Sorry, nevermind, seems it was a bit late yesterday: Didn't realise that the docker image has not enabled mqtt by default... (facepalm)

I downloaded and modified the dockerfile myself, added "RUN rabbitmq-plugins enable --offline rabbitmq_mqtt" and deployed as an app. Added some docker-options and now its working.
