### ISSUE TITLE
Is it possible to pass a queue config json at service creation time?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku-rabbitmq#33]
I have a json which defines some queues etc. I would like to perform teh setup from teh CLI, like demonstrated at http://blog.trestle-consulting.com/2013/03/rabbitmq-part-1-basic-configuration.html

```
./rabbitmqadmin import ~/broker-def.json -u example -p example
```

Is it possible to allow passing a json when invoking the plugin to create a new service?

Thanks!

**Comment by josegonzalez** [comment]
At the moment no. You'd need to run that command somehow else.

**Comment by sglebs** [comment]
According to @isaacsouza , it can be done like this:

```
curl -i -u financial-platform:1f0742317d7e198eb75b334d5028d54b -H "content-type:application/json" -X POST --data @rabbitmqs/financial-platform.json http://localhost:15673/api/definitions
```

It looks like it could be added as a feature to the cmd-line (json to pass in as setup).

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by josegonzalez** [comment]
Unfortunately there isn't a great way to do this, and I'm not inclined to implement it. Ideally the `rabbitmqadmin` could take stdin for specifying the file to import, in which case the answer would be something like:

```shell
dokku rabbitmq:enter test rabbitmqadmin import
```

However, thats not the case.

I'm going to close this for now, as the API is available for interested users, and the correct place to fix this is upstream (and then we can build an interface on top).

Note: this is related to how we don't support export/import in the rabbitmq service.
