### ISSUE TITLE
Using stomp + web-stomp plugin

### ISSUE THREAD

**Issue by olebedev** [dokku/dokku-rabbitmq#43]
Could you give me some tips about how to enable stomp and web-stomp plugin in dokku-rabbitmq?

**Comment by olebedev** [comment]
I was tried to set `RABBITMQ_CUSTOM_ENV="RABBITMQ_CONFIG_FILE=/var/lib/rabbitmq/rabbit.config;RABBITMQ_ENABLED_PLUGINS_FILE=/var/lib/rabbitmq/enabled_plugins"`, then create an instance, than put files into `/var/lib/dokku/services/rabbitmq/<instance>/data/*`. But, the rabbit log is:
```
=INFO REPORT==== 3-Jun-2016::05:54:22 ===
node           : rabbit@queue
home dir       : /var/lib/rabbitmq
config file(s) : /var/lib/rabbitmq/rabbit.config (not found)
cookie hash    : IVSveaV1TUJJoXwyAk99ZQ==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@queue
```
**(not found)** but file exists.

What I am doing wrong?

**Comment by weyert** [comment]
You can use your own Dockerfile which includes the plugin. Here is an example of RabbitMQ 3.7 with the `message_timestamp` and `delayed_message_exchange` plugins installed:
https://github.com/weyert/rabbitmq/blob/master/Dockerfile

**Comment by josegonzalez** [comment]
I would create a custom image and use that for your service. That also allows you to rollback potentially bad changes much easier, as the plugins are built into the image.
