### ISSUE TITLE
Web management panel access

### ISSUE THREAD

**Issue by olebedev** [dokku/dokku-rabbitmq#44]
Login failed each time. Trying to use credential from `dokku rabbitmq:info queue` command output.

**Comment by josegonzalez** [comment]
```
root@dokku:~# dokku rabbitmq:create test
       Waiting for container to be ready
^C=====> RabbitMQ container created: test
       DSN: amqp://test:2dc63f0eaf9ac9cabcfa510b0303ee43@dokku-rabbitmq-test:5672/test
root@dokku:~# dokku rabbitmq:expose test
-----> Service test exposed on port(s) 27374 14333 25085 18970
```

On my test server, after running expose, I was able to access the web ui via the following:

- `username`: `test`
- `password`: `2dc63f0eaf9ac9cabcfa510b0303ee43`

**Comment by olebedev** [comment]
Forgot to mention, I use direct IP address. Is it matter?

**Comment by josegonzalez** [comment]
You'll need the ip address of your host, but otherwise you can access it at:

- `HOST_IP_ADDRESS:4TH_EXPOSED_PORT`
