### ISSUE TITLE
Can't get acces to management panel

### ISSUE THREAD

**Issue by Rhjulskov** [dokku/dokku-rabbitmq#46]
Hi, 

I'm trying to get acces to the management panel by a custom default user and password:
export RABBITMQ_CUSTOM_ENV="RABBITMQ_DEFAULT_USER=user;RABBITMQ_DEFAULT_PASS=password"
dokku rabbitmq:create ...

It doesn't seem to work, and the quest / quest normal default combination is failing aswell.

**Comment by josegonzalez** [comment]
You mean `guest:guest`, not `quest:quest`?

**Comment by Rhjulskov** [comment]
Yes, the quest:quest is the default RabbitMQ Management user + password combination.

I'm able to pull the authentication information after the service has been created, but i'm not able to customize that with default user and password env variables as mentioned above.

So I have access, and the issue could just be closed.

**Comment by josegonzalez** [comment]
Again, it's not `quest:quest`, it is `guest:guest`, with a `g`, not a `q`.

**Comment by josegonzalez** [comment]
As well, we're setting the `RABBITMQ_DEFAULT_PASS` and `RABBITMQ_DEFAULT_USER` outside of the custom env as an override - which is what gives you the random password we have from `rabbitmq:info` - so thats probably why your custom stuff isn't working.

https://github.com/dokku/dokku-redis/issues/64 will track all the related work to allowing users to customize these options as necessary.
