### ISSUE TITLE
RAM and CPU's limit

### ISSUE THREAD

**Issue by dilame** [dokku/dokku-rabbitmq#48]
I have 4GB RAM VPS. I started dokku-rabbitmq, and i see 800gb memory limit
![2017-08-01 2 17 28](https://user-images.githubusercontent.com/9336742/28802543-a5846d22-765f-11e7-983e-084d15c5426a.png)
How can i increase it? I want to utilize all 4GB.

**Comment by josegonzalez** [comment]
You'll need to change a rabbitmq configuration file for that. You can get path info from the following command:

```
dokku rabbitmq:info SERVICE_NAME
```.
