### ISSUE TITLE
my app is linked to rabbitmq but environment variable RABBITMQ_URL is undefined

### ISSUE THREAD

**Issue by cocodrino** [dokku/dokku-rabbitmq#63]
Hi, I've an app "botengine_worker" linked to rabbitmq service "rabbitmq"

```
dokku rabbitmq:linked rabbitmq botengine_worker
-----> Service rabbitmq is linked to botengine_worker
```

my code try to read this env var but it always return undefined

```js
console.info("RABBITMQ env ", process.env["RABBITMQ_URL"])
```

do I need some extra step that I'm missing?...please let me know if you need more information or that I run some command...thank you so much

**Comment by josegonzalez** [comment]
Is the value set in `dokku config botengine_worker`?

**Comment by cocodrino** [comment]
Hi @josegonzalez pretty fast :sweat_smile: , yest it's set there

```
dokku config botengine_worker
 !     Deprecated: Use the 'config:show' command instead
=====> botengine_worker env vars
DOKKU_APP_TYPE:  dockerfile
GIT_REV:         4ba8d8daf89fe3b821cd2cdd1ae8faa02f417771
RABBITMQ_URL:    amqp://rabbitmq:c109xxx241f@dokku-rabbitmq-rabbitmq:5672/rabbitmq
```

**Comment by josegonzalez** [comment]
Environment variables are not available during dockerfile build, is that where you are having this issue?

If not, then try running `dokku ps:rebuild botengine_worker` and checking again.

**Comment by cocodrino** [comment]
not, it fails running the script, my dockerfile is really ~terrible~ simple

```
FROM node:10
RUN apt-get update || : && apt-get install python -y
WORKDIR /botengine
COPY /botengine .
RUN yarn run update:deps:yarn
RUN yarn run start:rt_worker
CMD [ "yarn","run", "start:rt_worker" ]
```

inside the running script I initialize a connection to rabbit,  the script starts with this code

```js
console.info("RABBITMQ env ", process.env["RABBITMQ_URL"])
```

and I get undefined there

**Comment by josegonzalez** [comment]
you should remove that `RUN yarn run start:worker` call. This attempts to start the process during the build.

**Comment by cocodrino** [comment]
oh crap...what a noob mistake :see_no_evil: !..I didn't even notice that I had these...you rock man :metal:  thanks!
